version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev_sql
    environment:
      - SA_PASSWORD=sql2022_
      - ACCEPT_EULA=Y
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-Psql2022_", "-Q", "select 1"]
        interval: 1s
        retries: 20
    ports:
      - "1435:1433"
    volumes:
      - db-data:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app/
    depends_on:
        db:
          condition: service_healthy
    environment:
      - DATABASE_URL=sqlsrv://sa:sql2022_@db/SecuriteSymfony
    
volumes:
  db-data: